Pilgrim 1610
OtacilioN/awesome-hacktoberfest-2020 pull request #223
Opened 2020-10-01 09:22 UTC by pilgrim-1610

## Contributing

If you want to add a project to this list, please make sure that:

- [ ] You read the [contributing guide](#CONTRIBUTING.md)
- [ ] The project can't be just an "add your name" or simply + 1 contribution to hacktoberfest
- [ ] Place them in alphabetical order
- [ ] One repository per PR/contribution - _avoid conflicts and simplify review_
- [ ] Your pull request is not spammy just adding an empty line, otherwise it will be marked as invalid and not count to hacktoberfest.

If they meet the requirements above, feel free to create a PR. Happy Hacking! :sparkles:

2020-10-01 13:31 UTC, OtacilioN commented on README.md
> +-[Python Mini-Project]
Can you add an empty space between the "-" and the "[" ?

Also remove the breakline, they should be in the same line

2020-10-01 13:32 UTC, OtacilioN commented on README.md
> +
Please remove this empty line.

2020-10-01 13:32 UTC, OtacilioN requested changes
Can you add an empty space between the "-" and the "[" ?

Also remove the breakline, they should be in the same line

2020-10-02 14:54 UTC, pilgrim-1610 commented on README.md
> +
On it

2020-10-04 15:34 UTC, OtacilioN commented
Now that's conflicts, but I think you already solved it in a new pull request right? Can I close this one? Fell free to reopen if you fix the conflicts and wants it to get merged.

2020-10-04 15:34 UTC, closed without merging